-- Flyway migration: create users/schemas for services (run with privileged user)
-- Note: Running as SYS may require specifying SYSDBA. This migration is for demo/dev only.

CREATE USER BOOKING_SCHEMA IDENTIFIED BY booking_pass;
GRANT CONNECT, RESOURCE TO BOOKING_SCHEMA;
GRANT CREATE SESSION, CREATE TABLE TO BOOKING_SCHEMA;

CREATE USER PAYMENT_SCHEMA IDENTIFIED BY payment_pass;
GRANT CONNECT, RESOURCE TO PAYMENT_SCHEMA;
GRANT CREATE SESSION, CREATE TABLE TO PAYMENT_SCHEMA;

CREATE USER LOYALTY_SCHEMA IDENTIFIED BY loyalty_pass;
GRANT CONNECT, RESOURCE TO LOYALTY_SCHEMA;
GRANT CREATE SESSION, CREATE TABLE TO LOYALTY_SCHEMA;

CREATE USER NOTIFICATION_SCHEMA IDENTIFIED BY notification_pass;
GRANT CONNECT, RESOURCE TO NOTIFICATION_SCHEMA;
GRANT CREATE SESSION, CREATE TABLE TO NOTIFICATION_SCHEMA;

CREATE USER SEAT_SCHEMA IDENTIFIED BY seat_pass;
GRANT CONNECT, RESOURCE TO SEAT_SCHEMA;
GRANT CREATE SESSION, CREATE TABLE TO SEAT_SCHEMA;
